 <%@ Page Language="C#" AutoEventWireup="true" CodeBehind="InventoryManagement.aspx.cs" Inherits="WebApplication2.InventoryManagement" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="StyleSheet1.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <h2>Inventory Management</h2>
        <p>&nbsp;</p>
        <br />
        <div>
            <table>
                <tr>
                    <td>ItemId</td>
                    <td><asp:TextBox ID="textbox3" runat="server"></asp:TextBox></td>
                    <td>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Please Enter Id" Display="Dynamic" ControlToValidate="textbox3" SetFocusOnError="True" ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td>ItemName:</td>
                    <td><asp:TextBox ID="textbox1" runat="server"></asp:TextBox></td>
                    <td>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Please Enter ItemName" Display="Dynamic" ControlToValidate="textbox1" SetFocusOnError="True" ForeColor="Red"></asp:RequiredFieldValidator>

                    </td>
                </tr>
                <tr>
                    <td>Quantity:</td>
                    <td><asp:TextBox ID="textbox2" runat="server"></asp:TextBox></td> 
                    <td>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Please Enter Quantity" Display="Dynamic" ControlToValidate="textbox2" SetFocusOnError="True" ForeColor="Red"></asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td colspan="4" align="center">
                        <asp:Button ID="btn1" Text="Add" runat="server" ForeColor="White" BackColor="Green" OnClick="btn1_Click" />
                        <asp:Button ID="btn2" Text="Next" runat="server" ForeColor="White" BackColor="Orange" PostBackUrl="~/BillingDetails.aspx" />

                    </td>
                </tr>
                <tr>
                    <td colspan="4" align="center">&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="4" align="center">
                        
                        
                        &nbsp;</td>
                </tr>
            </table>
            <asp:GridView runat="server" ID="GridView1" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" OnRowEditing="GridView1_RowEditing" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit">
                <Columns>
                    <asp:BoundField DataField="ItemId" HeaderText="ItemId" ReadOnly="true"></asp:BoundField>
                    <asp:BoundField DataField="ItemName" HeaderText="ItemName"></asp:BoundField>
                    <asp:BoundField DataField="Quantity" HeaderText="Quantity"></asp:BoundField>
                    </Columns>
                <Columns>

                    
                   
                </Columns>
               
            </asp:GridView>
        </div>
    </form>
</body>
</html>
